@startuml
class Usuario {
    - id: Long
    - nome: String
    - email: String
    - cpf: String
    - senha: String
    - registroCompleto: boolean
}

class Administrador {
    - id: Long
    - dataCriacao: LocalDate
}

class Participante {
    - id: Long
    - dataCriacao: LocalDate
}

class Dispositivo {
    - id: Long
    - identificadorBluetooth: UUID
    - imei: String
    - descricao: String
}

abstract class FotoRostoUsuario {
    - id: Long
    - arquivo: File
    - tipoMime: String
    - tamanhoArquivo: long
    - nomeArquivo: String
    - dataUpload: Date
}

class FotoRostoUsuarioLocal {
    - caminhoArquivo: String
}

class FotoRostoUsuarioS3 {
    - nomeBucket: String
    - chaveObjeto: String
}

class FotoRostoUsuarioAzure {
    - nomeContainer: String
}

class FotoRostoUsuarioGCloud {
    - nomeBucket: String
    - nomeObjeto: String
}

class Evento {
    - id: Long
    - descricao: String
    - permitirSolicitacoesIngresso: boolean
}

class SolicitacaoIngresso {
    - id: Long
    - codigo: String
    - dataHoraLimite: LocalDateTime
}

enum SituacaoSolicitacao {
    + PENDENTE
    + APROVADA
    + REJEITADA
}

class Localizacao {
    - id: Long
    - descricao: String
    - latitude: Double
    - longitude: Double
}

class RegistroPonto {
    - id: Long
    - data: LocalDate
    - emAndamento: boolean
}

class Ponto {
    - id: Long
    - horaInicio: LocalTime
    - minutosParaValidar: int
    - validado: boolean
}

class RegistroPresenca {
    - id: Long
    - dataHora: LocalDateTime
}

class RegistroPontoConfiguracao {
    - id: Long
    - raioPermitidoEmMetros: Float
}

enum Fator {
    + RECONHECIMENTO_FACIAL
    + LOCALIZACAO_INDOOR
}

RegistroPonto "*" --> "1" Evento
RegistroPonto "1" o-> "1" RegistroPontoConfiguracao
RegistroPonto "1" *-> "*" Ponto
RegistroPonto "*" *-> "*" Fator

Evento "*" --> "*" Administrador
Evento "1" --> "*" Localizacao
Evento "*" --> "*" Participante

SolicitacaoIngresso "*" o-> "1" Evento
SolicitacaoIngresso "*" o-> "1" SituacaoSolicitacao
SolicitacaoIngresso "*" o-> "1" Participante

RegistroPresenca "*" o-> "1" Participante
RegistroPresenca "*" o-> "1" Ponto
RegistroPresenca "1" o-> "1" FotoRostoUsuario

Usuario "1" o-> "*" Dispositivo
Usuario "1" *-> "1" FotoRostoUsuario

Administrador "1" --> "1" Usuario

Participante "1" --> "1" Usuario

FotoRostoUsuario <|-- FotoRostoUsuarioLocal
FotoRostoUsuario <|-- FotoRostoUsuarioS3
FotoRostoUsuario <|-- FotoRostoUsuarioAzure
FotoRostoUsuario <|-- FotoRostoUsuarioGCloud

@enduml
