@startuml
title Backend Application Class Diagram

class User {
    - id: Long
    - name: String
    - email: String
    - cpf: String
    - password: String
}

class Administrator {
    - id: Long
    - creationDate: LocalDate
}

class Participant {
    - id: Long
    - creationDate: LocalDate
}

class Device {
    - id: Long
    - bluetoothIdentifier: UUID
    - description: String
}

abstract class UserFacePhoto {
    - id: Long
    - file: File
    - mimeType: String
    - fileSize: long
    - fileName: String
    - uploadDate: Date
}

class UsedFactor {
     - id: Long
}

class LocalUserFacePhoto {
    - filePath: String
}

class S3UserFacePhoto {
    - bucketName: String
    - objectKey: String
}

class AzureUserFacePhoto {
    - containerName: String
}

class GCloudUserFacePhoto {
    - bucketName: String
    - objectName: String
}

class Environment {
    - id: Long
    - title: String
    - description: String
}

class Event {
    - id: Long
    - description: String
}

class Location {
    - id: Long
    - latitude: Double
    - longitude: Double
}


class PointRecord {
    - id: Long
    - date: LocalDate
}

class Point {
    - id: Long
    - startTime: LocalTime
    - minutesToValidate: int
    - validated: boolean
}

class AttendanceRecord {
    - id: Long
    - dateTime: LocalDateTime
}

interface Factor {
    + void {abstract} validate()
}

class FacialRecognitionFactor {
    - id: Long
    + void validate()
}

class IndoorLocationFactor {
    - id: Long
    - permittedRadiusInMeters: Float
    + void validate()
}

PointRecord "*" --> "1" Event
Event "*" --> "1" Environment
Environment "1" *-> "1" Administrator
Event "*" --> "*" Administrator
Event "1" --> "1" Location

PointRecord "1" *-> "*" Point
PointRecord "*" o-> "*" Factor

AttendanceRecord "*" o-> "1" Participant
AttendanceRecord "*" o-> "1" Point
AttendanceRecord "1" o-> "1" UserFacePhoto

Factor <|-- FacialRecognitionFactor
Factor <|-- IndoorLocationFactor

IndoorLocationFactor "*" o-> "1" Device

User "1" o-> "*" Device
User "1" *-> "1" UserFacePhoto

AttendanceRecord "1" *-> "*" UsedFactor
UsedFactor "1" --> "1" Factor

Administrator "1" --> "1" User
Participant "1" --> "1" User

UserFacePhoto <|-- LocalUserFacePhoto
UserFacePhoto <|-- S3UserFacePhoto
UserFacePhoto <|-- AzureUserFacePhoto
UserFacePhoto <|-- GCloudUserFacePhoto

@enduml